
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 10 21:54:54 CST 2025
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Elseif = 8;
  public static final int Else = 7;
  public static final int Parentesis_c = 26;
  public static final int For = 9;
  public static final int Parentesis_a = 25;
  public static final int Suma = 21;
  public static final int Numero = 33;
  public static final int Op_booleano = 14;
  public static final int ERROR = 34;
  public static final int Break = 13;
  public static final int Identificador = 32;
  public static final int Comillas = 2;
  public static final int Int = 4;
  public static final int Llave_c = 28;
  public static final int Llave_a = 27;
  public static final int Op_relacional = 18;
  public static final int P_coma = 30;
  public static final int T_dato = 3;
  public static final int Main = 29;
  public static final int Cadena = 5;
  public static final int EOF = 0;
  public static final int Division = 24;
  public static final int Op_incremento = 19;
  public static final int Resta = 22;
  public static final int PI = 16;
  public static final int If = 6;
  public static final int Linea = 31;
  public static final int Return = 12;
  public static final int error = 1;
  public static final int Do = 11;
  public static final int Igual = 20;
  public static final int Multiplicacion = 23;
  public static final int While = 10;
  public static final int NULL = 15;
  public static final int MAX_INT = 17;
}

